// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIfVf4Oorrx5NghHDetsa-0KFMHxIBo9E',
    appId: '1:98467410254:web:5f4822ea6d1c8be0b02e1f',
    messagingSenderId: '98467410254',
    projectId: 'flutter-chat-app-d4fcd',
    authDomain: 'flutter-chat-app-d4fcd.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d4fcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAly3tnschpAjM3QHyj6fcHa3kdassO27c',
    appId: '1:98467410254:android:e9d72abd11cb87b4b02e1f',
    messagingSenderId: '98467410254',
    projectId: 'flutter-chat-app-d4fcd',
    storageBucket: 'flutter-chat-app-d4fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAqqP00OXVdFLxV5dbD68HZSclViMR1xw',
    appId: '1:98467410254:ios:df1729bf7cdcc244b02e1f',
    messagingSenderId: '98467410254',
    projectId: 'flutter-chat-app-d4fcd',
    storageBucket: 'flutter-chat-app-d4fcd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAqqP00OXVdFLxV5dbD68HZSclViMR1xw',
    appId: '1:98467410254:ios:df1729bf7cdcc244b02e1f',
    messagingSenderId: '98467410254',
    projectId: 'flutter-chat-app-d4fcd',
    storageBucket: 'flutter-chat-app-d4fcd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIfVf4Oorrx5NghHDetsa-0KFMHxIBo9E',
    appId: '1:98467410254:web:56003651c20ece52b02e1f',
    messagingSenderId: '98467410254',
    projectId: 'flutter-chat-app-d4fcd',
    authDomain: 'flutter-chat-app-d4fcd.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d4fcd.appspot.com',
  );

}